Remove extraneous type: ignore comment
Otherwise, mypy fails with:
python/lsst/pipe/base/tests/mocks/_data_id_match.py:38: error: Unused
"type: ignore" comment  [unused-ignore]
Found 1 error in 1 file (checked 78 source files)
    Error: Process completed with exit code 1.