Skip automodapi for BuildId and DatasetType Name
These types cause a documentation build failure:

  FileNotFoundError: [Errno 2] No such file or directory: '/j/ws/sqre/infra/documenteer/doc_template/_build/doctree/py-api/lsst.pipe.base.BuildId.doctree'

Presumably because Sphinx/autodoc doesn't understand that they are generated
by typing.NewType rather than being fully-fledged classes.