Fix bug in Task.display's handling of source argument
If the source argument to Task.display was a source catalog
(instead of a collection of source catalogs) then this:
sources[0][0]
which was expected to raise TypeError or NotImplementedError
if sources was a catalog, would fail with:
AttributeError: 'int' object has no attribute 'get'
Apparently new catalogs don't support sources[0][0].
I fixed this and simplified the test.