graph: fix mypy failure in DefaultLoadHelper.load
python/lsst/pipe/base/graph/_loadHelpers.py:254: error: Argument 1 to UUID has incompatible type UUID; expected Optional[str]
python/lsst/pipe/base/graph/_loadHelpers.py:254: error: Subclass of UUID and str cannot exist: would have incompatible method signatures

The declared type of 'nodes' didn't match how it was being used
(declared as iterable of UUID, but treated as if it might be
an iterable of strings or UUID). Fixed the declared types rather
than changing the behaviour.

Looks like this only started showing up in mypy 0.950.